### ISSUE TITLE
Formating Issue

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#13]
Hi.

I can't use HTML to format some entries. I need to use \n. Is there a way to make the text bold?

`      "description": "Você pode bloquear raios blaster com o Caminho (resistir com Convicção).\n\nSe resistir a um ataque de blaster, você pode gastar 1 de estresse para redirecionar o fogo e fazer seu próprio ataque com ele.",`

**Comment by drewg13** [comment]
That sounds like a Foundry issue not specific to my system. I know Foundry sanitizes a lot of fields. If you want more specific advice, you'll have to be much more specific about what you're trying to do and where.

**Comment by brunocalado** [comment]
I want to use **BOLD**. But, I can't use HTML tags in some places. I need to use \n for linebreaks in these places.

Do you know a way to add bold in these cases?

Thank you.

![image](https://user-images.githubusercontent.com/4999783/132748433-2863bdb0-8e04-40ce-9bc8-be63615eb8c5.png)

![image](https://user-images.githubusercontent.com/4999783/132748463-2af8f3b0-d776-4472-aac2-2f53fff30ab0.png)

**Comment by drewg13** [comment]
I'm still not understanding, as your example seems to show \n working just fine. For bold, I would use <strong></strong> html tags. 

But this does not appear to be specific to this system, as nothing I'm doing would be stripping out any html coding, so doesn't really belong here as an issue.

**Comment by drewg13** [comment]
My subconscious chewed on this for awhile and I recalled that using triple braces is a thing for some fields:
https://handlebarsjs.com/guide/expressions.html#html-escaping
I still am totally unclear on what you're trying to do and how you're trying to do it, because you've provided very little information, but this may help.  The only other option for formatting text in forms that is supported in stock Foundry is to use `{{editor}}` instead of `<textarea>`, but that's massive overkill for what should be simple item descriptions, so I'm not really interested in going that far.
