### ISSUE TITLE
[Macro] Job Creation Macro

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#21]
This macro uses job tables to create a job. You can click the button to generate a journal.

If you want to use it. You need to change the name of the tables to english

![image](https://user-images.githubusercontent.com/4999783/133706856-71cdc169-085c-4ed4-8bf5-0024b1c2928c.png)

[scum-villainy_work - Copia.txt](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7181747/scum-villainy_work.-.Copia.txt)

**Comment by drewg13** [comment]
That's neat, I'll look into fleshing that out.

**Comment by brunocalado** [comment]
I add the tables for names. Small update.

You need to create or copy the tables: 
https://perchance.org/pdq8o9qplc#edit
![image](https://user-images.githubusercontent.com/4999783/133713859-a263af86-9a35-4bd2-9fd2-39128fb12ab0.png)


[Forged in the Dark.zip](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7182100/Forged.in.the.Dark.zip)

**Comment by drewg13** [comment]
I made some modifications to the macro, but it's been added.

**Comment by drewg13** [comment]
So I made some updates to your macro that you may want to backport:

1.  You're giving your button an html id of "createJob", but ids should be unique, so I built in a randomID() element to it
2.  I moved the folder creation logic to the createJob function, so it's not creating the folder until someone tries to save a job
3.  The addEventListenerOnHtmlElement function needed some changes, as it wasn't working if the chat log was popped out:  Hooks.once became Hooks.on in order to catch both renders of the chat message and I had to put in a null test to prevent console log error floods on every chat window re-render
4.  I simplified the drawFromTable function a bit and made it back-compatible with version 0.7.X

I think that's all, but let me know if you have questions or further improvements to it.

**Comment by drewg13** [comment]
[scum-jobs-macro.txt](https://github.com/drewg13/foundryvtt-scum-and-villainy/files/7672648/scum-jobs-macro.txt)

**Comment by brunocalado** [comment]
Thank you very much.

**Comment by brunocalado** [comment]
I updated mine. Very nice! 

I have something extra on my macro. I don't if you want to add to yours. I create 2 NPCs and add then to the journal. I'm using tables from page 62. But, I only have them in portuguese.



```js
  msg+= `<br>`;
  msg+= await createPeople();
  msg+= `<br>`;
  msg+= await createPeople(); 
  
  async function createPeople() {
  const name1 = await drawFromTable('Nomes');
  const surname = await drawFromTable('Sobrenomes');
  const aparen1 = await drawFromTable('Aparência - Identidade');
  const aparen2 = await drawFromTable('Aparência');
  const alias = await drawFromTable('Codinomes');

  let msg = `<h2>${name1} ${surname} (${alias})</h2>`;
  msg += `<ul><li>Sugestão de Identidade: <b>${aparen1}</b></li>`;
  msg += `<li>Aparência: <b>${aparen2}</b></li></ul>`;
  
  return msg;
}
```
