### ISSUE TITLE
Tooltip Issue

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#29]
Hi.

If the text from the tooltip is to big it will show hide. You can scrolldown, but this will make the tooltip disapear.

![image](https://user-images.githubusercontent.com/4999783/135539894-d8fc7ec0-2607-4267-b416-e63c4784beaf.png)

Tks

**Comment by drewg13** [comment]
I've been aware of this one since the beginning and haven't found a way to fix it.  The tooltip is restricted to the size of the window and can't go outside it.  The only way I can think of to completely fix it is to expand the window with a ridiculous amount of blank space at the bottom, but that looks absurd.  I'll add a few lines for now, but unless some other solution presents itself, the solution will have to be to just look up the few problem items in the compendium or book.
