### ISSUE TITLE
Potentially incorrect loads

### ISSUE THREAD

**Issue by curtishay** [drewg13/foundryvtt-scum-and-villainy#4]
I'm loving the system work that you've done and I'm looking to use it for a Star Wars themed game I'm about to start, but I found a few things when I was testing it out that might need attention. 

I believe the following loads are incorrect:

- (My) Offerings should be 1 instead of 0
- (My) Outdated Religious Outfit should be 0 instead of 1
- (P) Fine Small Urbot should be 0 instead of 2
- (S) Armor should be 2 instead of 1
- (S) Heavy Blaster should be 2 instead of 1
- (S) Medkit should be 2 instead of 1
- (S) Spacesuit should be 2 instead of 1
- (Sp) Large Luxury item (load 2) is missing

**Comment by drewg13** [comment]
It looks like you're getting your values from the playsheets, while I got mine directly from the book.  I have the latest errata, which does not clarify any of this, so I defer to the book on the first three.  I did miss the 2 load Standard items, because the loads for standard items are not directly specified in the book, and I'll also differentiate between the 0, 1, and 2 load Speaker luxury items, so thanks for catching those.
