### ISSUE TITLE
Small Improvements to Actor Sheet Style

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#46]
Hi. I tried, but I can't match css, html. 

Would be possible to you to make small improvements to the actor sheet?

![Sem título](https://user-images.githubusercontent.com/4999783/146653415-51f88265-4ef5-4ed7-8ba3-ade621c3d35a.png)

**Comment by drewg13** [comment]
Some of this I can't do:
 - change the alignment of the healing clock relative to its zero label

Some of this I have no idea what you're trying to suggest:
 -  the black lines near cred/stash, when that area is fully in use rather than empty, most of that space is necessary

Some of it I prefer the way it is:
 - the attribute/skills alignments, I think a center alignment looks terrible personally.
 - the Effects tab is gated behind isGM so that only the GM sees it, but I find it useful for debugging and resolving occasional issues during play, so I'm not going to remove it.

I did do some tweaking in the Harm/Healing/Armor section that lines things up better, but CSS/HTML is definitely my weakest area, so I'm not inclined to spend a lot of time on it.

**Comment by brunocalado** [comment]
Thank you.

I suggested:
- Move the name input box to the side of the label name. 
- Move the alias input box to the side of the alias name. 
- Move Current Load to to the site of Loadout: **Loadout - Current Load** 
- Remove look field.

**Comment by drewg13** [comment]
Those make a lot of sense now that you've elaborated, except removing the Look field.  That's a default field that's present on the sheets provided by the system, so I'm not removing that.

**Comment by drewg13** [comment]
![image](https://user-images.githubusercontent.com/1455026/146657002-f85fa2cd-6aff-4885-96e1-b5eaff963f69.png)
Yeah, I like this a lot better.  Good suggestions.
