### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#49]
Hi

The translation for fortune roll add **BITD.**. I don't know why.
![image](https://user-images.githubusercontent.com/4999783/150550052-34fe6541-1782-4f06-905e-d5c3a0bf8678.png)

**Comment by drewg13** [comment]
That happens when the localization function can't find the string in the language file. I'm guessing it has something to do with the '!'. If that string in your translation module has the '!', try removing it.  If it doesn't have it, try adding it. I can't recall which is correct off the top of my head.

**Comment by drewg13** [comment]
Nope, nevermind that. I know what it is and how to fix it. Just a weird unexpected interaction with how I parse rolls.

**Comment by drewg13** [comment]
Fixed in 1.15.1
