### ISSUE TITLE
Combat Tracker

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#51]
Hi.

System like sav don't need a Combat Tracker. But, It's useful in many situations. If you tested the PBTA system you notice the CT works. I use it just to organize people anxiety lol.

If possible, please make it let you add chars to it and change the position.

**Comment by drewg13** [comment]
I see what you mean with this, it looks like it doesn't work because I don't have a default initiative formula set.  I can just do what PBTA does and set it to 1d20.  This would give you a random initiative for each Actor in the tracker.  You could then change it however you like.  Changing the initiative order is a little fiddly, but if there's a system out there that does it more cleanly, let me know and I'll take a look at that system.

**Comment by drewg13** [comment]
Adding and removing Actors is already possible by toggling the Combat State button on their tokens.

**Comment by drewg13** [comment]
Done in 1.15.2.
