### ISSUE TITLE
Improve Item UI

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#53]
Hi

Can you improve the item UI?

I want to add a big description to this Ur Artifact, but I can't format or link fvtt entities.
![image](https://user-images.githubusercontent.com/4999783/151701518-8a81970b-57f9-4de7-b430-c27ee831da88.png)

Suggestions:

- [ ] Turn the description field into a standard foundry journal. You can format, you link stuff, you can add css, when you spam to the chat it can be nicely formated etc
- [ ] Move the class field to the side of load. To much useless space.
- [ ] Move effects to a title link or somewhere. Is AE useful for items? If so, can you share some snippets?

**Comment by drewg13** [comment]
I don't know what you mean by "standard foundry journal", that's not a thing.  Do you mean a TinyMCE field instead of a textarea?
Effects are useful, I had plans to increase a PCs Attune skill and decrease their Study skill automatically to reflect the narrative effects of an Ur artifact making them more attuned to the Way, but less attuned to the physical world.  They didn't go that route, but it could be done.

**Comment by brunocalado** [comment]
Sorry, yes. TinyMCE 
![image](https://user-images.githubusercontent.com/4999783/151970516-b1cdd902-afc3-4189-929e-9277ab7e77dd.png)

**Comment by drewg13** [comment]
v 1.15.3
