### ISSUE TITLE
Current Loadout not updating

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-scum-and-villainy#56]
Hi.

I want to request the current loadout to show on Party Overview module. But, the actor don't seen to have this information updated.
    "loadout": {
      "current": 0,

**Party Overview Module**
![image](https://user-images.githubusercontent.com/4999783/151721325-3bca7ca4-6a98-4b69-b084-43327652d5ba.png)

**Comment by drewg13** [comment]
That's not going to work because loadout.current is calculated dynamically in the actor's getData() function based on whatever items are attached to the actor on each update.  It's not really practical to save it to the DB and would require a pretty extensive re-write or a total reconfiguration of the way I use Items.

**Comment by brunocalado** [comment]
oh boy... ok

**Comment by drewg13** [comment]
Figured out a way to do this cleanly while fixing other things in V2.1.1.  Not sure why I didn't think of it before, but there it is.
