### ISSUE TITLE
atrtibutes should go up to 4

### ISSUE THREAD

**Issue by mjol22** [drewg13/foundryvtt-scum-and-villainy#63]
there's an errata on [Evil Hat's website](https://www.evilhat.com/home/scum-and-villainy-downloads/) that states 
"Page 10: Attribute Rating is from zero to 4."

**Comment by drewg13** [comment]
You've misread the errata. Attributes are Insight, Prowess, and Resolve, which go to 4 instead of 3 because each has 4 related Action Ratings. Action Ratings go to 3, not 4.  That errata is correcting a typo on the page, that's all.  Also, see the response by Sean Nittner in the comments on the page you linked:

Sean Nittner
Posted May 10, 2019 at 12:24 AM
Hi Alonso, the max value for action and Action (Helm, Scramble, etc) is 3, which is correct on the sheet. The max value of the Attribute (Insight, Prowess, etc) is 4.
