### ISSUE TITLE
Can't Add Trauma

### ISSUE THREAD

**Issue by the-bowmanizer** [drewg13/foundryvtt-scum-and-villainy#65]
I am running Scum and Villainy 2.1.2 on Foundry V10 Testing 5 (build 279). Likely this is an issue with the new testing version.

Trauma is no longer being calculated and I can not add new traumas. Existing traumas are still marked so long as I do not toggle them off and back on - in that case they do not persist and disappear entirely.

You can see in the screenshot that this character has two traumas set but a trauma level of 0 in the center.

![image](https://user-images.githubusercontent.com/105297243/186931291-f7bd52d9-c120-4118-8d0a-63497243f1aa.png)

**Comment by drewg13** [comment]
Thanks for calling attention to this, looks like some of the new input validations in V10 caught up with me.  Those `input`s now all need a `data-dType="Boolean"` on them and it clears right up.  This is an issue for all of my systems, unfortunately for me.

Any character that fell afoul of this shouldn't need to be recreated, once you update and use those UI elements again.  Let me know if you have trouble though.

Fixed in next version.
