### ISSUE TITLE
Needs Updated For/To Errata

### ISSUE THREAD

**Issue by SasugaTV** [drewg13/foundryvtt-scum-and-villainy#67]
According to the official errata the initial upkeep should be 1.

More importantly, Actions should go up to four, not three. Which is more inline with Blades in the Dark and Band of Blades.

Official Errata (They use Google Docs)
https://docs.google.com/document/d/1D013JUUtrVIq3XKO0EaRMof3TW5fzvtPwMI7T1_U25E/edit

The Official Errata can be found on their official website.
https://evilhat.com/product/scum-and-villainy/

**Comment by the-bowmanizer** [comment]
You’ve misunderstood the errata. Attribute ratings go up to 4 - as in prowess, resolve, and insight. Action ratings are correctly capped at 3.

**Comment by drewg13** [comment]
This has been brought up multiple times before.  I really wish people would approach this with a touch of humility instead of assuming they're correct and I'm wrong.  It's just rude.

Action Ratings are not the same thing as the Attribute Ratings mentioned in the Errata.  Additionally, here is a statement on the subject from Sean Nittner on the Evil Hat website commenting to someone else making the same error:

Sean Nittner
Posted May 10, 2019 at 12:24 AM
Hi Alonso, the max value for action and Action (Helm, Scramble, etc) is 3, which is correct on the sheet. The max value of the Attribute (Insight, Prowess, etc) is 4.

**Comment by drewg13** [comment]
You've also misunderstood the "initial upkeep" errata, although it could be more clearly explained.  The book states:
> To calculate your upkeep costs, add your crew quality to all system quality ratings and divide by four, rounding down.  Most ships will have an upkeep of 2 to start.
The errata states:
> Starting upkeep should be 1 by default.

The point is not that upkeep should be set to a floor of 1.  The point is that, once you've gone through ship creation, adding the base values for your ship type plus the two additional ship systems improvements of your choice, you can expect to have a starting upkeep of 1.  The book incorrectly listed that expected value as 2, so the errata corrects it to 1, but it's just about what you should expect to see if you've correctly followed the process, not some hard floor in the value.

**Comment by SasugaTV** [comment]
Ah, thanks!
