### ISSUE TITLE
Sync Universe Jobs and Status with Faction Overview Actor

### ISSUE THREAD

**Issue by fhtagnn** [drewg13/foundryvtt-scum-and-villainy#85]
I just played a little bit with all the different actors and noticed that the the universe actor works independently of the faction overview actor. If you add the same faction without first adding it to your items from the companion then even the faction clock is not synced. If the faction ist added as an item then it at least shows the same faction clock if clicked/opened. 

Would it be possible to have both actors show the same status and job number? I wanted to restrict the universe to myself as GM because of the faction clocks show and have a separate faction overview for the players to check their status.

**Comment by drewg13** [comment]
In theory, that's hypothetically possible.  However, in Foundry, Items attached to Actors are copies, not references, so they are independent of each other.  Keeping Items synced like that would be somewhat impractical and would break some other use-cases.  Additionally, using a different sheet to hide faction goal information would not work, as players would just click through from the faction overview sheet to see the faction Item sheet, which contains the faction goal information you're talking about hiding.  There is no way to prevent this, other than hiding the existence of the faction from the players entirely by using the eye icon, which is available on either sheet.


I'm not going to tell you how to run your game, but generally speaking, keeping secrets from each other is a very D&D-brain thing and isn't considered good practice in FitD games.  The intended mode of play is for everyone at the table to share information to come up with the best narrative possible in the moment, rather than the D&D practice of a GM constructing a narrative in advance for players to reveal during play.  In FitD, we lay all the information on the table about the current state of the world and play to find out what happens.  Broad faction goals and their progress are very much things your *players* should know, even if their *characters* do not, because sometimes players come up with cooler ideas than GMs.


The inclusion of the two separate methods of faction tracking came about from player-submitted code when they wanted a cleaner interface to track a larger number of factions than was practical on the universe sheet.  It was and is not intended for keeping hidden information or for having two independent interfaces for the same information.
